import React from 'react';

import {
  Strawberry,
  Rose,
  Raspberry,
  Pomegranate,
  Plum,
  Peach,
  Orange,
  Lemon,
  Grapes,
  Grapefruit,
  Cherries,
  Blueberries,
  Bergamot,
  Hibiscus,
  Apple,
  Melon,
  Honey,
  Coconut,
  Cinnamon,
  Hazelnut,
  Caramel,
  Sugar,
  Vanilla,
  Chocolate,
  Guava,
  Blackberry,
  Pear,
  Pineapple,
  Mango,
  Kiwi
} from '../utils/medallion/FlavorMedallions';

export const FLAVORS = {
  "caramel": <Caramel width="20px"/>,
  "jasmine": <Rose width="20px" color="#E2D069"/>,
  "pomegranate": <Pomegranate width="20px"/>,
  "orange blossom": <Orange width="20px"/>,
  "orange": <Orange width="20px"/>,
  "grapefruit": <Grapefruit width="20px"/>,
  "bakers chocolate": <Chocolate width="20px"/>,
  "milk chocolate": <Chocolate width="20px"/>,
  "chocolate": <Chocolate width="20px"/>,
  "dark chocolate": <Chocolate width="20px"/>,
  "brown sugar": <Sugar width="20px"/>,
  "sugar": <Sugar width="20px"/>,
  "hazelnut": <Hazelnut width="20px"/>,
  "honey": <Honey width="20px"/>,
  "honeysuckle": <Honey width="20px"/>,
  "lime": <Bergamot width="20px"/>,
  "rose hips": <Rose width="20px"/>,
  "stone fruit": <Peach width="20px"/>,
  "plum": <Plum width="20px"/>,
  "red grapes": <Grapes width="20px"/>,
  "grapes": <Grapes width="20px"/>,
  "vanilla": <Vanilla width="20px"/>,
  "raspberry": <Raspberry width="20px"/>,
  "peach": <Peach width="20px"/>,
  "lemon": <Lemon width="20px"/>,
  "melon": <Melon width="20px"/>,
  "apple": <Apple width="20px"/>,
  "green apple": <Apple width="20px" color="#357035"/>,
  "red apple": <Apple width="20px"/>,
  "hibiscus": <Hibiscus width="20px" />,
  "cherry": <Cherries width="20px" />,
  "black cherry": <Cherries width="20px" />,
  "sweet cherries": <Cherries width="20px" />,
  "cinnamon": <Cinnamon width="20px" />,
  "strawberry": <Strawberry width="20px"/>,
  "fermented strawberry": <Strawberry width="20px"/>,
  "strawberry jam": <Strawberry width="20px"/>,
  "coconut": <Coconut width="20px"/>,
  "floral": <Rose width="20px"/>,
  "bergamot": <Bergamot width="20px"/>,
  "lemon": <Lemon width="20px"/>,
  "guava": <Guava width="20px"/>,
  "blackberry": <Blackberry width="20px"/>,
  "pear": <Pear width="20px"/>,
  "pineapple": <Pineapple width="20px"/>,
  "mango": <Mango width="20px"/>,
  "kiwi": <Kiwi width="20px"/>,
}
