import React from 'react';

import {
  Strawberry,
  Rose,
  Raspberry,
  Pomegranate,
  Plum,
  Peach,
  Orange,
  Lemon,
  Grapes,
  Grapefruit,
  Cherries,
  Blueberry,
  Bergamot,
  Hibiscus,
  Apple,
  Melon,
  Honey,
  Coconut,
  Cinnamon,
  Hazelnut,
  Caramel,
  Sugar,
  Vanilla,
  Chocolate,
  Guava,
  Blackberry,
  Pear,
  Pineapple,
  Mango,
  Kiwi,
  Lavender,
  PassionFruit,
  BlackCurrant,
  Watermelon,
  Figs,
  Lychee,
  Tea,
  Nougat,
  Marshmallow,
  Rhubarb,
  Almond,
  Cardamom,
  Pistachio,
  Meringue,
  Bubble,
  Elderflower,
  CreamSoda,
  RedWine,
  LimeCheesecake,
  Nutmeg,
  Waffle,
  MapleSyrup,
  Geranium,
} from '../utils/medallion/FlavorMedallions';

export const FLAVORS = {
  "caramel": <Caramel />,
  "jasmine": <Rose  color="#E2D069"/>,
  "pomegranate": <Pomegranate />,
  "orange blossom": <Orange />,
  "orange": <Orange />,
  "grapefruit": <Grapefruit />,
  "bakers chocolate": <Chocolate />,
  "milk chocolate": <Chocolate />,
  "chocolate": <Chocolate />,
  "dark chocolate": <Chocolate />,
  "brown sugar": <Sugar />,
  "sugar": <Sugar />,
  "hazelnut": <Hazelnut />,
  "honey": <Honey />,
  "honeysuckle": <Honey />,
  "lime": <Bergamot />,
  "rose hips": <Rose />,
  "stone fruit": <Peach />,
  "plum": <Plum />,
  "red grapes": <Grapes />,
  "raisins": <Grapes />,
  "grapes": <Grapes />,
  "vanilla": <Vanilla />,
  "raspberry": <Raspberry />,
  "peach": <Peach />,
  "lemon": <Lemon />,
  "melon": <Melon />,
  "apple": <Apple />,
  "green apple": <Apple  color="#357035"/>,
  "red apple": <Apple />,
  "hibiscus": <Hibiscus  />,
  "cherry": <Cherries  />,
  "black cherry": <Cherries  />,
  "sweet cherries": <Cherries  />,
  "cinnamon": <Cinnamon  />,
  "strawberry": <Strawberry />,
  "fermented strawberry": <Strawberry />,
  "strawberry jam": <Strawberry />,
  "coconut": <Coconut />,
  "floral": <Rose />,
  "bergamot": <Bergamot />,
  "lemon": <Lemon />,
  "guava": <Guava />,
  "blackberry": <Blackberry />,
  "pear": <Pear />,
  "pineapple": <Pineapple />,
  "mango": <Mango />,
  "kiwi": <Kiwi />,
  "lavender": <Lavender />,
  "passion fruit": <PassionFruit />,
  "black currant": <BlackCurrant />,
  "red currant": <BlackCurrant color="#AF2543" />,
  "watermelon": <Watermelon />,
  "nectarine": <Peach />,
  "violet": <Lavender />,
  "molasses": <Honey color="#783429" />,
  "figs": <Figs />,
  "lychee": <Lychee />,
  "green tea": <Tea />,
  "nougat": <Nougat />,
  "honeycomb": <Honey />,
  "cane sugar": <Sugar />,
  "white flower": <Rose />,
  "marshmallow": <Marshmallow />,
  "black tea": <Tea color="#282627" />,
  "rhubarb": <Rhubarb />,
  "toffee": <Caramel />,
  "nutella": <Chocolate />,
  "rose": <Rose />,
  "tangerine": <Orange />,
  "cacao nibs": <Chocolate />,
  "papaya": <Guava />,
  "blueberries": <Blueberry />,
  "blueberry": <Blueberry />,
  "almond": <Almond />,
  "rooibos": <Tea color="#ED4726" />,
  "lily": <Hibiscus />,
  "vanilla cake": <Vanilla />,
  "cherry blossom": <Cherries />,
  "cocoa": <Chocolate />,
  "red ripe fruits": <Strawberry />,
  "red fruits": <Strawberry />,
  "dried fruits": <Plum />,
  "cranberry": <Pomegranate />,
  "blackberry soda": <Blackberry />,
  "cherry liquor": <Cherries />,
  "cardamom": <Cardamom />,
  "pistachio": <Pistachio />,
  "kaffir lime": <Bergamot />,
  "candied lemon": <Lemon />,
  "berries": <Strawberry />,
  "clementine": <Orange />,
  "meringue": <Meringue />,
  "lemonade": <Lemon />,
  "bubble": <Bubble />,
  "prosecco": <Bubble />,
  "elderflower": <Elderflower />,
  "apricot": <Peach />,
  "cream soda": <CreamSoda />,
  "purple fruits": <Plum />,
  "tropical fruits": <Mango />,
  "red wine": <RedWine />,
  "honeydew": <Melon />,
  "wild berries": <Strawberry />,
  "creamy": <Marshmallow />,
  "juniper berries": <BlackCurrant />,
  "raspberry jam": <Raspberry />,
  "lime cheesecake": <LimeCheesecake />,
  "kumquat": <Orange />,
  "walnut": <Hazelnut />,
  "mandarin": <Orange />,
  "nutmeg": <Nutmeg />,
  "waffle": <Waffle />,
  "maple syrup": <MapleSyrup />,
  "juicy rhubarb": <Rhubarb />,
  "geranium": <Geranium />,
}
