import React from 'react';

import {
  Strawberry,
  Rose,
  Raspberry,
  Pomegranate,
  Plum,
  Peach,
  Orange,
  Lemon,
  Grapes,
  Grapefruit,
  Cherries,
  Blueberries,
  Bergamot
} from '../utils/medallion/FlavorMedallions';

export const FLAVORS = {
  "caramel": <Rose width="20px"/>,
  "jasmine": <Rose width="20px" color="#E2D069"/>,
  "pomegranate": <Pomegranate width="20px"/>,
  "orange blossom": <Orange width="20px"/>,
  "orange": <Orange width="20px"/>,
  "bakers chocolate": <Pomegranate width="20px"/>,
  "milk chocolate": <Pomegranate width="20px"/>,
  "chocolate": <Pomegranate width="20px"/>,
  "dark chocolate": <Pomegranate width="20px"/>,
  "brown sugar": <Pomegranate width="20px"/>,
  "hazelnut": <Pomegranate width="20px"/>,
  "honey": <Pomegranate width="20px"/>,
  "honeysuckle": <Pomegranate width="20px"/>,
  "lime": <Bergamot width="20px"/>,
  "rose hips": <Rose width="20px"/>,
  "stone fruit": <Rose width="20px"/>,
  "plum": <Plum width="20px"/>,
  "red grapes": <Grapes width="20px"/>,
  "grapes": <Grapes width="20px"/>,
  "vanilla": <Grapes width="20px"/>,
  "raspberry": <Raspberry width="20px"/>,
  "peach": <Peach width="20px"/>,
  "lemon": <Lemon width="20px"/>,
  "melon": <Lemon width="20px"/>,
  "apple": <Strawberry width="20px"/>,
  "green apple": <Strawberry width="20px"/>,
  "red apple": <Strawberry width="20px"/>,
  "hibiscus": <Rose width="20px" />,
  "cherry": <Cherries width="20px" />,
  "black cherry": <Cherries width="20px" />,
  "sweet cherries": <Cherries width="20px" />,
  "cinnamon": <Cherries width="20px" />,
  "strawberry": <Strawberry width="20px"/>,
  "fermented strawberry": <Strawberry width="20px"/>,
  "strawberry jam": <Strawberry width="20px"/>,
  "coconut": <Strawberry width="20px"/>,
  "floral": <Rose width="20px"/>,
  "bergamot": <Bergamot width="20px"/>,
  "lemon": <Lemon width="20px"/>,
}
